@startuml
left to right direction
:Ciudadano: -- (Registrar entrada)
:Ciudadano: <|- :Ciudadano extranjero:
:Ciudadano extranjero: -- (Tomar huellas)
(Registrar entrada) <. (Tomar huellas) : <<extend>>
@enduml