@startuml
left to right direction
actor "Cliente" as c
rectangle {
  usecase "Mostrar menú" as UC1
  usecase "Pedir comida" as UC2
}
c -- UC1
c -- UC2
UC1 -- :Restaurante:
(Entregar comida) -- :Restaurante:
@enduml